export * from './about'; 
export * from './background'; 
export * from './contact'; 
export * from './home'; 
export * from './myProjects'; 
export * from './skill'; 
export * from './myProject2'; 
export * from './myProject3'; 
export * from './myProject4'; 